### ISSUE TITLE
Some fixes on steps component

### ISSUE THREAD

**Issue by jmjuanes** [jmjuanes/siimple#70]
When a large text is displayed in `siimple-steps-item-description`, it breaks the steps item display:

![image](https://user-images.githubusercontent.com/5751201/57390070-ca65c100-71bb-11e9-8544-796a9987a243.png)

But when the width of the `siimple-steps-item` is fixed:

![image](https://user-images.githubusercontent.com/5751201/57433294-659c7c00-7238-11e9-9203-3a25f2c86fd4.png)

### Solution

Add the following sentences to the `siimple-steps-item` element:

```css
.siimple-steps-element {
    width: 150px; 
    vertical-align: top;
}
```
