### ISSUE TITLE
Redesign tip element

### ISSUE THREAD

**Issue by jmjuanes** [jmjuanes/siimple#72]
### Redesign tip element

Current status of the tip element: 
![image](https://user-images.githubusercontent.com/5751201/63876307-87776580-c9c5-11e9-87e5-e7cdaaeb1124.png)

Idea of the new tip design: 
![image](https://user-images.githubusercontent.com/5751201/63876202-5008b900-c9c5-11e9-931f-b4c146126b79.png)

Changes made for the new tip design:

```css
.siimple-tip {
    display: block;
    position: relative;
    /* width: calc(100% - 25px - 20px - 5px); */
    border-left-style: solid;
    border-left-width: 30px;
    border-radius: 5px;
    padding-top: 10px;
    padding-right: 10px !important;
    padding-bottom: 10px;
    padding-left: 15px !important;
    margin-bottom: 20px;
    /* background-color: #eef2f7; */
    font-size: 16px;
    color: #546778;
    line-height: 24px;
}
```

### Things to do

- [x] Change background color and change the with of the border-left.
- [x] Redesign old icons.
- [x] Add new icons:
    - Info
    - Cross
    - Check
